[package]
name = "dataframe-manip"
version = "0.1.0"
authors = ["Mick1406 <mick.carraz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.12.0"
